# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/actions/assets-action"
      - "/actions/branch-action"
      - "/actions/cdxgen"
      - "/actions/charts-values-update-action"
      - "/actions/chart-version"
      - "/actions/container-package-cleanup"
      - "/actions/custom-event"
      - "/actions/docker-action"
      - "/actions/docker-config-resolver"
      - "/actions/ghcr-discover-repo-packages"
      - "/actions/maven-release"
      - "/actions/maven-snapshot-deploy"
      - "/actions/metadata-action"
      - "/actions/poetry-publisher"
      - "/actions/pr-add-messages"
      - "/actions/pr-assigner"
      - "/actions/smart-download"
      - "/actions/store-input-params"
      - "/actions/tag-action"
      - "/actions/verify-json"
      - "/actions/wait-for-workflow"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/actions/assets-action"
      - "/actions/container-package-cleanup"
      - "/actions/custom-event"
      - "/actions/metadata-action"
      - "/actions/pr-assigner"
    schedule:
      interval: "weekly"
