# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/actions/archive-and-upload-assets"
      - "/actions/assets-action"
      - "/actions/container-package-cleanup"
      - "/actions/custom-event"
      - "/actions/metadata-action"
      - "/actions/pom-updater"
      - "/actions/pr-assigner"
      - "/actions/tag-checker"
    schedule:
      interval: "weekly"