name: "Wait for Workflow"
description: "Ожидает завершение указанного workflow"
inputs:
  workflow:
    description: "Имя файла workflow (например build.yml)"
    required: true
  ref:
    description: "Ветка или SHA, для которой нужно ждать (опционально)"
    required: false
    default: ${{ github.ref }}
  token:
    description: "GitHub Token для аутентификации (опционально)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Wait for workflow to finish
      shell: bash
      run: |
        echo "Waiting for workflow '${{ inputs.workflow }}' on ref '${{ inputs.ref }}' to complete..."
        echo "Fetching workflow runs..."
        runs_json=$(gh run list \
          --workflow "${{ inputs.workflow }}" \
          --branch "${{ inputs.ref }}" \
          --json databaseId,status,conclusion,event,headBranch,headSha,displayTitle,createdAt \
          --limit 20)

        echo "$runs_json" | jq .
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
