name: "Wait for Workflow"
description: "Ожидает завершение указанного workflow"
inputs:
  workflow:
    description: "Имя файла workflow (например build.yml)"
    required: true
  ref:
    description: "Ветка или SHA, для которой нужно ждать (опционально)"
    required: false
    default: ${{ github.ref }}
  pr_number:
    description: "Номер pull request, для которого нужно ждать (опционально)"
    required: false
  token:
    description: "GitHub Token для аутентификации (опционально)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Wait for workflow to finish
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        GH_REPO: ${{ github.repository }}
        WORKFLOW: ${{ inputs.workflow }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        echo "⏳ Waiting for workflow '${WORKFLOW}' triggered by PR #${PR_NUMBER}..."

        run_id=$(gh api "repos/${GH_REPO}/actions/runs" \
          --jq "([.workflow_runs[]
                  | select(.event==\"pull_request\")
                  | select(.pull_requests[].number == ${PR_NUMBER})
                  | select(.name == \"${WORKFLOW}\")
                  | .id][0])")

        if [ -z "$run_id" ] || [ "$run_id" = "null" ]; then
          echo "❌ Workflow '${WORKFLOW}' for PR #${PR_NUMBER} not found."
          exit 1
        fi

        echo "✅ Found workflow run ID: $run_id"
        gh run watch "$run_id" --exit-status

