runs:
  using: "composite"
  steps:
    - name: Wait for workflow to finish
      shell: bash
      run: |
        echo "Waiting for workflow '${{ inputs.workflow }}' on ref '${{ inputs.ref }}' to complete..."
        gh run watch \
          --workflow "${{ inputs.workflow }}" \
          --ref "${{ inputs.ref }}" \
          --exit-status

    - name: Show workflow details
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        echo "Fetching details for workflow '${{ inputs.workflow }}'..."
        gh run list \
          --workflow "${{ inputs.workflow }}" \
          --ref "${{ inputs.ref }}" \
          --limit 1 \
          --json databaseId,displayTitle,status,conclusion,url \
          --jq '.[] | "Run: \(.displayTitle)\nStatus: \(.status)\nConclusion: \(.conclusion)\nURL: \(.url)"'
