name: "Wait for Workflow"
description: "Ожидает завершение указанного workflow"
inputs:
  workflow:
    description: "Имя файла workflow (например build.yml)"
    required: true
  ref:
    description: "Ветка или SHA, для которой нужно ждать (опционально)"
    required: false
    default: ${{ github.ref }}
  token:
    description: "GitHub Token для аутентификации (опционально)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Wait for workflow to finish
      shell: bash
      run: |
        echo "Waiting for workflow '${{ inputs.workflow }}' on ref '${{ inputs.ref }}' to complete..."
        gh run list \
        --workflow "${{ inputs.workflow }}" \
        --branch "${{ inputs.ref }}" \
        --json databaseId,status,conclusion
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
