name: "Wait for Workflow"
description: "Wait for a specific GitHub Actions workflow to complete for a given pull request."
inputs:
  workflow:
    description: "Workflow name (sample: build.yml)"
    required: true
  ref:
    description: "Ветка или SHA, для которой нужно ждать (optional)"
    required: false
    default: ${{ github.ref }}
  pr-number:
    description: "Номер pull request, для которого нужно ждать (optional)"
    required: false
  timeout:
    description: "Max time to wait in minutes (optional)"
    required: false
    default: "30"
  poll-interval:
    description: "Polling interval in seconds (optional)"
    required: false
    default: "10"
  compact:
    description: "Use compact output (optional)"
    required: false
    default: "false"
  token:
    description: "GitHub Token для аутентификации (optional)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Wait for workflow to finish
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        GH_REPO: ${{ github.repository }}
        WORKFLOW: ${{ inputs.workflow }}
        PR_NUMBER: ${{ inputs.pr-number }}
        TIMEOUT: ${{ inputs.timeout }}
        POLL_INTERVAL: ${{ inputs.poll-interval }}
        COMPACT: ${{ inputs.compact }}
      run: |
        echo "⏳ Waiting for workflow '${WORKFLOW}' triggered by PR #${PR_NUMBER}..."

        run_id=$(gh api "repos/${GH_REPO}/actions/runs" \
          --jq "([.workflow_runs[]
                  | select(.event==\"pull_request\")
                  | select(.pull_requests[].number == ${PR_NUMBER})
                  | select(.name == \"${WORKFLOW}\")
                  | .id][0])")

        if [ -z "$run_id" ] || [ "$run_id" = "null" ]; then
          echo "❌ Workflow '${WORKFLOW}' for PR #${PR_NUMBER} not found."
          exit 1
        fi

        COMPACT_FLAG=""
        if [ "${COMPACT}" = "true" ]; then
           COMPACT_FLAG="--compact"
        fi

        echo "✅ Found workflow run ID: $run_id"

        timeout "${TIMEOUT}" gh run watch "$run_id" --interval "${POLL_INTERVAL}" {COMPACT_FLAG} --exit-status
