name: "Wait for Workflow"
description: "Ожидает завершение указанного workflow"
inputs:
  workflow:
    description: "Имя файла workflow (например build.yml)"
    required: true
  ref:
    description: "Ветка или SHA, для которой нужно ждать (опционально)"
    required: false
    default: ${{ github.ref }}
  token:
    description: "GitHub Token для аутентификации (опционально)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Wait for workflow to finish
      shell: bash
      run: |
        run_id=$(gh api repos/${GH_REPO}/actions/runs \
          --jq ".workflow_runs[]
            | select(.event==\"pull_request\")
            | select(.pull_requests[].number == ${PR_NUMBER})
            | select(.name == \"${WORKFLOW}\")
            | .id" \
          | head -n1)

        if [ -z "$run_id" ]; then
          echo "❌ Workflow '${WORKFLOW}' for PR #${PR_NUMBER} not found."
          exit 1
        fi

        echo "✅ PR #${PR_NUMBER} run workflow '${WORKFLOW}' (Run ID: $run_id)"
        echo "Waiting for end..."

        gh run watch "$run_id" --exit-status

      env:
        GITHUB_TOKEN: ${{ inputs.token }}
