name: Feature request
description: Suggest an idea for this project
labels: [enhancement,feature]
title: "[Feature]: "
projects: ["Netcracker/13"]
type: Feature
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        A clear and concise description of what the feature is.
      placeholder: |
        <one sentence capability>
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: |
        A clear and concise description of what the problem is.
      placeholder: |
        <why current state is insufficient>
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks / Considerations
      description: "Risks / Considerations"
      placeholder: |
        <compatibility, security, performance>
    validations:
      required: true
