name: Feature request
description: Suggest an idea for this project
labels: [enhancement,feature]
title: "[Feature]: "
projects: ["Netcracker/13"]
type: Feature
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        A clear and concise description of what the feature is.
      placeholder: |
        <one sentence capability>
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: |
        A clear and concise description of what the problem is.
      placeholder: |
        <why current state is insufficient>
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks / Considerations
      description: "Risks / Considerations"
      placeholder: |
        <compatibility, security, performance>
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        A clear and concise description of what the solution is.
      placeholder: |
        <high-level behaviour; avoid deep implementation details>
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope / Boundaries
      description: |
        In scope: ...
        Out of scope: ...
      placeholder: |
        In scope: ...
        Out of scope: ...
    validations:
      required: false
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: "Acceptance Criteria"
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Alternatives Considered"
      placeholder: |
        - Option A – why rejected
        - Option B – why rejected
    validations:
      required: false
  - type: textarea
    id: followup
    attributes:
      label: Follow-up / Future
      description: "Followup items"
      placeholder: |
        <items deliberately deferred>
    validations:
      required: false
