---

# Input parameter project_type is optional.
# If not provided, the script will try to detect the project type automatically.
# More info on possible values for project_type can be found there:
# https://cyclonedx.github.io/cdxgen/#/PROJECT_TYPES

name: "Generate SBOM file for project"
description: "Generate Software Bill of Materials (SBOM) file for the project and CycloneDX vulnerability report"

inputs:
  project_type:
    description: "Type of the project"
    required: false

runs:
  using: "composite"
  steps:

    - name: "Checout code"
      uses: actions/checkout@v4

    - name: "Check input"
      shell: bash
      run: |
        if [[ "${{ inputs.project_type }}" != "" ]]
        then
          echo "Project type is provided: ${{ inputs.project_type }}"
          echo "PROJECT_TYPE=-t ${{ inputs.project_type }}" >> $GITHUB_ENV
        else
          echo "Project type is not provided"
          echo "PROJECT_TYPE=" >> $GITHUB_ENV
        fi

    - name: "Generate BOM"
      run: |
        cd ${GITHUB_WORKSPACE}
        export FETCH_LICENSE=true
        docker run --rm -e FETCH_LICENSE=true -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen:v8.6.0 -r /app -p -o /app/${{ github.event.repository.name }}_sbom.json "${{ env.PROJECT_TYPE }}"
        docker rmi -f $(docker images -aq)
      shell: bash

    - name: "Upload SBOM file"
      uses: actions/upload-artifact@v4.6.0
      with:
        name: "BOM file"
        path: ${{ github.workspace }}/**/${{ github.event.repository.name }}_sbom.json
        retention-days: 5

    - name: "Generate Depscan report"
      run: |
        cd ${GITHUB_WORKSPACE}
        export FETCH_LICENSE=true
        docker run --rm -e FETCH_LICENSE=true -v $PWD:/app ghcr.io/owasp-dep-scan/dep-scan --src /app \
        --reports-dir /app/reports --bom /app/${{ github.event.repository.name }}_sbom.json
      shell: bash

    - name: "Upload Depscan report"
      uses: actions/upload-artifact@v4.6.0
      with:
        name: "DEPSCAN report"
        path: ${{ github.workspace }}/**/reports/*
        retention-days: 5
