rules:
  github-env:
    disable: true
  template-injection:
    disable: true
  use-trusted-publishing:
    disable: true
  secrets-outside-env:
    disable: true
  dangerous-triggers:
    ignore:
      - cla.yaml
      - pr-assigner.yml
