name: "Update XML Node"
description: "Updates an XML node in a specified file using an XPath expression."

inputs:
  file_path:
    description: "The path to the XML file to update."
    required: false
    default: '{"default": "pom.xml"}'
  path:
    description: "The XPath expression to locate the node to update. Defaults to `//p:project/p:properties/p:revision`."
    required: false
    default: "//p:project/p:properties/p:revision"
  new_value:
    description: "The new value to set for the selected XML node."
    required: true
outputs:
  artifact_id:
    description: "The artifact ID of the updated XML file."

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "edit"
  color: "blue"
