name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  try-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Try to assign reviewers
        run: |
          ASSIGNEES=( $(yq eval '.assignees[]' ./.github/pr-assigner-config.yml) )
          ARGS=()
          for assignee in "${ASSIGNEES[@]}"; do
              ARGS+=(--add-assignee "$assignee")
          done
          PR_NUMBER="${{ github.event.pull_request.number }}"
          gh pr edit "$PR_NUMBER" "${ARGS[@]}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}