---
name: Create tag (Obsolete)
on:
  workflow_call:
    inputs:
      tag-name:
        required: true
        type: string
        description: 'Tag version'
      ref:
        description: "Branch name to create tag from"
        required: false
        type: string
        default: main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Display deprecation warning
        run: echo "::warning::💥🚀 This reusable workflow is deprecated. Will be removed soon."

      - name: Input parameters
        run: |
          echo "Tag version: ${{ inputs.tag-name }}" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.ref || github.ref_name }}

      - name: Create tag
        run: |
          git config --global user.email "qubership-actions[bot]"
          git config --global user.name "qubership-actions[bot]@qubership.com"
          git tag -a ${{ inputs.tag-name }} -m "Tag ${{ inputs.tag-name }}"

      - name: Push tag
        run: git push origin ${{ inputs.tag-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}